### ISSUE TITLE
Modal scrollable shadow

### ISSUE THREAD

**Issue by andreipfeiffer** [SynetoNet/compass-react#12]
to show that there's more content you can scroll:
https://codepen.io/TofuBot/pen/obydpM

**Comment by chindrisadrian** [comment]
In the docs there is a shadow when there is no content scrolled
![image](https://user-images.githubusercontent.com/15315220/59759094-05b5de00-9298-11e9-9dc5-2c57a99ddbd1.png)

check example code
https://codepen.io/chindrisadi/pen/wbbRWM

**Comment by andreipfeiffer** [comment]
Reverted back to the more complex implementation.
The one with the local background is nice and simple, but the problem is that is uses backgrounds, which render "under" the content.

So, any element with a background will appear "above" the shadow, and will cover it, which looks weird.
