### ISSUE TITLE
Tab content is not displaying

### ISSUE THREAD

**Issue by denisdenes** [SynetoNet/compass-react#18]
The tab's content is not displaying in our project, because the `show` class is not present on the active tabpanel. The `active` class toggling works.

Workaround: using the `transition={false}` prop, fixes it (removes the .fade:not(.show) from css)

**Comment by andreipfeiffer** [comment]
Fixed in `0.4.3` https://github.com/SynetoNet/compass-react/commit/b006cd4104cf130b51848b5c9bd9d24ce03400be
